# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
