# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='repassword',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
